### ISSUE TITLE
What to do about broken Evals?

### ISSUE THREAD

**Issue by damhack** [declare-lab/instruct-eval#21]
As reported by Phillip and Joshua over at AI Explained, most LLM benchmarks are broken due to incomplete or incorrect dataset items.  E.g., In the case of MMLU, c. 2% of questions are meaningless or wrong.

[https://youtu.be/hVade_8H8mE](https://youtu.be/hVade_8H8mE?si=Qa1DYoLrWuym5aPo)

Some people argue that some "label noise" is to be expected in datasets and we should just live with it.  This view conflates noise in training models with noise in eval datasets.  They are very different beasts (train/sft vs. inference) and have different impacts on LLM behaviour.

The narrow band of scores towards the top of leaderboards would suggest that eval noise is capable of significantly skewing results.

The question then is, What To Do?

We can either carry on regardless, ignoring the elephant in the room.  Or we can start a community effort to fix the benchmarks, either by reviewing and filtering out bad data, or fixing the data.

It would have to be a community effort because of the size and complexity of some of the datasets.

Any thoughts?

**Comment by soujanyaporia** [comment]
Very insightful post. I would not bother about such noisy evaluation datasets. Several other datasets are subjective and noisy too e.g., popular sentiment analysis benchmarks. We should try to explore ways to curate more challenging benchmarks such as BBH, human-eval, etc. In our latest effort, we created benchmarks or ways to test LLM's safety and found GPT-4, ChatGPT could be red-teamed successfully about 69% of the time -- one of the several possible future research directions.

However, I do agree that reducing noise from the eval datasets is an important task. But I am unsure whether such efforts should be made on the existing datasets or we rather focus on creating more challenging and clean benchmarks.
